pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub-creds-id'
        DOCKER_IMAGE          = 'moreirafernandoj/springboot-app'
        DOCKER_REGISTRY       = 'https://index.docker.io/v1/'
        REPO_URL              = 'https://github.com/fmoreira13/devops-24-25-1241905.git'
        JAVA_HOME             = '/opt/java/openjdk'
        PATH                  = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando o código...'
                git branch: 'main', url: env.REPO_URL
            }
        }

        stage('Criar Dockerfile') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    echo 'Creating Dockerfile...'
                    script {
                        writeFile file: 'Dockerfile', text: '''
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
'''
                    }
                }
            }
        }

        stage('Assemble') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    sh '''
                        chmod +x gradlew
                        ./gradlew clean assemble
                    '''
                }
            }
        }

        stage('Testes') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    sh './gradlew test'
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

         stage('Javadoc') {
             steps {
                 dir('CA1/Part3/react-and-spring-data-rest-basic') {
                     sh './gradlew javadoc'
                     publishHTML(target: [
                         reportDir: 'build/docs/javadoc',
                         reportFiles: 'index.html',
                         reportName: 'Documentação Javadoc',
                         allowMissing: false,
                         keepAll: true,
                         alwaysLinkToLastBuild: true
                     ])
                 }
            }
         }

        stage('Arquivar JAR') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    script {
                        def app = docker.build("${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}", '.')
                        docker.withRegistry(env.DOCKER_REGISTRY, env.DOCKER_CREDENTIALS_ID) {
                            app.push()
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}