pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando o repositório público...'
                git url: 'https://github.com/fmoreira13/devops-24-25-1241905.git', branch: 'main'
            }
        }
        stage('Assemble') {
            steps {
                dir('CA1/Part2/gradle_basic_demo') {
                    echo 'Compilando a aplicação...'
                    sh 'chmod +x gradlew'
                    sh './gradlew clean assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('CA1/Part2/gradle_basic_demo') {
                    echo 'Executando testes...'
                    sh './gradlew test'
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                dir('CA1/Part2/gradle_basic_demo') {
                    echo 'Arquivando artefatos...'
                    archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
                }
            }
        }
    }
}
