pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'cred-git', url: 'https://github.com/fmoreira13/devops-24-25-1241905.git'
            }
        }
        stage('Assemble') {
            steps {
                sh './gradlew assemble'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
                junit 'build/test-results/test/*.xml'
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
            }
        }
    }
}
